name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build
    - name: Publish
      run: dotnet publish --configuration Release --no-build -o published_output
    - name: Set up SSH
      run: |
        echo -e "${{secrets.DEPLOYMENT_KEY}}" > key
        chmod 600 key
    - name: Deploy to target system
      run: scp -i key -o StrictHostKeyChecking=no -r published_output "${{secrets.DEPLOYMENT_USER}}@${{secrets.DEPLOYMENT_HOST}}:/home/${{secrets.DEPLOYMENT_USER}}/rsc/"
    - name: Clean up SSH
      if: always()
      run: shred -n 5 -u key
      
      
      
      


